# Laptop only
[[profile]]
name = "laptop"

[[profile.output]]
search = ["m=0x40A9", "v=Lenovo Group Limited"]
enable = true
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
exec = ['sh -c "ln -sf ~/.config/hypr/monitors/hyprlock-laptop.conf ~/.config/hypr/hyprlock.conf"']

# External monitor connected
[[profile]]
name = "docked"

[[profile.output]]
search = ["m=0x40A9", "v=Lenovo Group Limited"]
enable = false

[[profile.output]]
search = ["m=MSI G241", "v=Microstep"]
enable = true
mode = "1920x1080@144Hz"
position = "0,0"
scale = 1.0
exec = ['sh -c "ln -sf ~/.config/hypr/monitors/hyprlock-external.conf ~/.config/hypr/hyprlock.conf"']
