"$schema" = 'https://starship.rs/config-schema.json'

format = """
$jobs\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = '[➜](bold purple)'
error_symbol = '[➜](bold red)'

[directory]
style = 'blue'
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 2
truncation_symbol = '󰇘/'
truncate_to_repo = true
read_only = ' '
read_only_style = 'red'

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'wallpapers' = ' '

[git_branch]
style = 'green'
symbol = '󰘬 '
format = '[$symbol$branch ]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold red'
conflicted = '='
ahead = '⇡$count'
behind = '⇣$count'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'
typechanged = ""

[fill]
symbol = ' '

[nodejs]
symbol = ' '
detect_files = ["package.json"]
format = '[$symbol($version )]($style)'

[jobs]
symbol = '✦'
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'bold yellow'
format = '[$duration]($style)'
