format = """
$jobs\
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$rust\
$package\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = '[➜](bold purple)'
error_symbol = '[➜](bold red)'

[directory]
style = 'blue'
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 2
truncation_symbol = '󰇘/'
truncate_to_repo = true 
read_only = ' '
read_only_style = 'red'

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'wallpapers' = ' '

[git_branch]
style = 'green'
symbol = '󰘬 '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold red'
conflicted = '='
ahead = '⇡$count'
behind = '⇣$count'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = ''
typechanged = ""

[fill]
symbol = ' '

[python]
symbol = ' '

[lua]
symbol = ' '

[nodejs]
symbol = ' '
detect_files = ["package.json", ".nvmrc"]

[golang]
symbol = ' '
disabled = true

[haskell]
symbol = ' '
disabled = true

[rust]
symbol = ' '

[c]
symbol = ' '
disabled = true

[cpp]
symbol = ' '
disabled = true

[java]
symbol = ' '
disabled = true

[ruby]
symbol = ' '
disabled = true

[package]
format = 'on [$symbol$version]($style)' 

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'
disabled = true

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']

[jobs]
symbol = '✦'
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'bold yellow'
format = '[$duration]($style)'
