# Hyprlock config for my laptop monitor

source = $HOME/.cache/wal/colors-hyprland

# General
general {
    hide_cursor = true
    grace = 0
}

# Background
background {
    monitor =
    path = $wallpaper
    blur_size = 5
    blur_passes = 3
    brightness = 0.7
    vibrancy = 0.15
}

# Password Field
input-field {
    monitor =
    size = 100, 30
    position = 0, 10
    halign = center
    valign = center

    rounding = 20
    outline_thickness = 0

    inner_color = rgba(220, 225, 252, 0.2)
    outer_color = rgba(220, 225, 252, 0.2)
    check_color = rgba(192, 202, 245, 0.15)
    fail_color = rgba(247, 118, 142, 0.20)
    capslock_color = rgba(230, 150, 165, 0.25)

    font_color = rgba(220, 225, 252, 0.45)
    font_family = JetBrains Mono

    dots_center = true
    dots_text_format = 󰫢
    dots_size = 0.35
    dots_spacing = 0.5


    fade_on_empty = true
    fade_timeout = 200
    placeholder_text = <i></i>

    fail_text = <b>FAIL</b>
    fail_timeout = 300
    shadow_color = rgba(175, 185, 225, 0.16)
    shadow_passes = 2
    shadow_size = 8
}

# Time
label {
    monitor =
    text = cmd[update:1000] date +"%I:%M"
    color = rgba(220, 225, 252, 0.2)
    font_family = Angel wish
    font_size = 200
    position = 0, 270
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d, %Y"
    color = rgba(220, 225, 252, 0.3)
    font_family = Angel wish
    font_size = 20
    shadow_passes = 0
    shadow_size = 4
    position = -20,-5
    halign = right
    valign = top
}

# Greeting
label {
    monitor =
    text = hello $USER
    color = rgba(220, 225, 252, 0.3)
    font_family = Angel wish
    font_size = 20
    shadow_passes = 0
    shadow_size = 4
    position = 20,-5
    halign = left
    valign = top
}
