[Setting]
inject_theme_js        = 0
replace_colors         = 1
check_spicetify_update = 0
spotify_path           = /opt/spotify/
prefs_path             = /home/houssam/.config/spotify/prefs
current_theme          = snippets
color_scheme           = 
inject_css             = 1
overwrite_assets       = 0
spotify_launch_flags   = 
always_enable_devtools = 0

[Preprocesses]
remove_rtl_rule    = 1
expose_apis        = 1
disable_sentry     = 1
disable_ui_logging = 1

[AdditionalOptions]
sidebar_config        = 0
home_config           = 1
experimental_features = 1
extensions            = CoverAmbience.js|loopyLoop.js|shuffle+.js
custom_apps           = 

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.84.476.ga1ff6607
with    = 2.43.1
