# Shell & terminal
set -g default-shell /bin/zsh
set -g default-terminal 'tmux-256color'

set -ga terminal-overrides ',*:RGB'
set -as terminal-overrides ',*:sitm=\E[3m'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Prefix
set -g prefix C-Space
unbind C-b

# Performance
set -g escape-time 0
set -g history-limit 1000000

# General behavior
set -g mouse on
set -g set-clipboard on
set -g detach-on-destroy off
set -g allow-passthrough on
set -g focus-events on

# Indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Reload config
unbind r
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Splits
unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# New window
bind c new-window -c "#{pane_current_path}"

# Resize panes
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Zoom
bind -r m resize-pane -Z

# kill commands
bind x kill-pane
bind X kill-window
bind Q kill-session

# Window navigation
bind -r H previous-window
bind -r L next-window

# Session navigation
bind -r J switch-client -n
bind -r K switch-client -p

# Copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
unbind -T copy-mode-vi MouseDragEnd1Pane

# Custom script bindings
bind g run-shell "open-github"
bind f new-window -n "sessions" tmux-sessionizer
bind i new-window -n "cht" tmux-cht
bind t new-window -n "timefor" timefor
bind G new-window -n "lazygit" lazygit

# Misc bindings
bind E show-environment -g
bind b if-shell -F '#{==:#{status},on}' \
	'set-option -t:. status off' \
	'set-option -t:. status on'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'msc5/tmux-smart-pane'

set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# Theme colors
set -g @gray_light   "#c5c8c6"
set -g @gray_medium  "#585858"
set -g @gray_dark    "#303030"
set -g @green_soft   "#87af87"
set -g @blue_muted   "#5f87af"
set -g @cyan_soft    "#5fafaf"

# Status bar
set -g status-position top
set -g status-justify absolute-centre
set -g status-interval 1
set -g status-left-length 100

set -g status-style "fg=#{@gray_light},bg=default"
set -g status-left "#[fg=#{@green_soft},bold]#S #[fg=#{@gray_light},nobold]"
set -g status-right "#{?@time_category, #{@time_category} #{@time_total},}"

# Windows status
set -g window-status-current-format "#[fg=#{@cyan_soft},bold] #I:#W*"
set -g window-status-format " #I:#W"

# Messages & modes
set -g message-style "fg=#{@gray_light},bg=default"
set -g mode-style "fg=#{@gray_dark},bg=#{@blue_muted}"

# Pane borders
set -g pane-border-style "fg=#{@gray_dark}"
set -g pane-active-border-style "fg=#{@green_soft}"

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
