# ------------------------------
# general
# shell, terminal, behavior
# ------------------------------
set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -as terminal-overrides ',*:sitm=\E[3m'

# prefix
set -g prefix C-Space
unbind C-b

# performance
set -g escape-time 0
set -g history-limit 1000000

# qol
set -g mouse on
set -g set-clipboard on
set -g detach-on-destroy off
set -g allow-passthrough on

# indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# focus events
set -g focus-events on

# ------------------------------
# keybinds
# ------------------------------
# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# splits
unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# new window
bind c new-window -c "#{pane_current_path}"

# resize
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# zoom
bind -r m resize-pane -Z

# kill
bind x kill-pane
bind X kill-window
bind Q kill-session

# ------------------------------
# navigation
# ------------------------------
# panes (vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# windows
bind -r H previous-window
bind -r L next-window

# sessions
bind -r J switch-client -n
bind -r K switch-client -p

# ------------------------------
# copy mode
# vi + system clipboard
# ------------------------------
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# disable mouse copy
unbind -T copy-mode-vi MouseDragEnd1Pane

# ------------------------------
# custom scripts
# ------------------------------
bind g run-shell "open-github"
bind f new-window -n "sessions" tmux-sessionizer
bind i new-window -n "cht" tmux-cht
bind t new-window -n "timefor" timefor
bind G new-window -n "lazygit" lazygit

# misc
bind E show-environment -g
bind b set -g status

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# ------------------------------
# theme
# ------------------------------
set -g @gray_light   "#c5c8c6"
set -g @gray_medium  "#585858"
set -g @gray_dark    "#303030"
set -g @green_soft   "#87af87"
set -g @blue_muted   "#5f87af"
set -g @cyan_soft    "#5fafaf"

# status bar
set -g status-position top
set -g status-justify absolute-centre
set -g status-interval 1
set -g status-left-length 100

set -g status-style "fg=#{@gray_light},bg=default"
set -g status-left "#[fg=#{@green_soft},bold] #S #[fg=#{@gray_light},nobold]"
set -g status-right "#{?@time_category, #{@time_category} #{@time_total},}"

# windows
set -g window-status-current-format "#[fg=#{@cyan_soft},bold] #I:#W*"
set -g window-status-format " #I:#W"

# ui
set -g message-style "fg=#{@gray_light},bg=default"
set -g mode-style "fg=#{@gray_dark},bg=#{@blue_muted}"

# borders
set -g pane-border-style "fg=#{@gray_dark}"
set -g pane-active-border-style "fg=#{@green_soft}"

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
