# General Settings
set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -as terminal-overrides ',*:sitm=\E[3m'

set -g prefix C-Space
unbind C-b

set -g escape-time 0
set -g history-limit 1000000
set -g mouse on
set -g set-clipboard on
set -g detach-on-destroy off
set -g allow-passthrough on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on

# Key Bindings
unbind r
bind r source-file ~/.config/tmux/tmux.conf;

unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# Vi-mode Copy
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

unbind -T copy-mode-vi MouseDragEnd1Pane

# Custom Scripts & Tools
bind i run-shell "tmux neww ~/.config/scripts/tmux-cht.sh"
bind s new-window "~/.config/scripts/tmux-session-fzf.sh"
bind g run-shell "~/.config/scripts/open-github.sh"
bind t new-window -n "Time" "bash ~/.config/scripts/time.sh"
bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/dotfiles"
bind G new-window -n "lazygit" lazygit
bind E show-environment -g
bind b set -g status

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# Theme 
set -g @gray_light   "#c5c8c6"
set -g @gray_medium  "#585858"
set -g @gray_dark    "#303030"
set -g @green_soft   "#87af87"
set -g @blue_muted   "#5f87af"
set -g @cyan_soft    "#5fafaf"

set -g status-position top
set -g status-justify absolute-centre
set -g status-interval 1
set -g status-left-length 100

set -g status-style "fg=#{@gray_light},bg=default"
set -g status-left "#[fg=#{@green_soft},bold] #S #[fg=#{@gray_light},nobold]"
set -g status-right "#{?@time_category, #{@time_category} #{@time_total},}"

set -g window-status-current-format "#[fg=#{@cyan_soft},bold] #I:#W*"
set -g window-status-format " #I:#W"

set -g message-style "fg=#{@gray_light},bg=default"
set -g mode-style "fg=#{@gray_dark},bg=#{@blue_muted}"

set -g pane-border-style "fg=#{@gray_dark}"
set -g pane-active-border-style "fg=#{@green_soft}"

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
