### General ###
k             cycle ontop
f             cycle fullscreen

### Video ###
d             cycle deband
D             cycle deinterlace
n             cycle video-unscaled

.             frame-step
,             frame-back-step

### Audio ###
a             cycle audio
A             cycle audio down

UP            add volume 2
DOWN          add volume -2
WHEEL_UP      add volume 2
WHEEL_DOWN    add volume -2

x             add audio-delay -0.05
X             add audio-delay +0.05

### Subtitles ###
j             cycle sub
J             cycle sub down
v             cycle sub-visibility

=             add sub-scale +0.05
-             add sub-scale -0.05

z             add sub-delay -0.05
Z             add sub-delay +0.05

U             cycle blend-subtitles
p             cycle sub-fix-timing
g             sub-reload

### Playlist ###
Ctrl+RIGHT    playlist-next
Ctrl+LEFT     playlist-prev

TAB           script-binding playlistmanager/showplaylist

### Statistics ###
i             script-binding stats/display-stats-toggle

### uosc ###
MBTN_RIGHT    script-binding uosc/menu
