### Playback ###
profile=high-quality
keep-open=yes
save-position-on-quit
force-seekable=yes
hr-seek=yes

### Video ###
video-sync=display-resample
deband=no

### User Interface ###
border=no
osd-bar=no
cursor-autohide=300
cursor-autohide-fs-only=yes

### On-Screen Display (OSD) ###
osd-font=JetBrains Mono
osd-font-size=22

### Subtitles ###
sub-auto=all
sub-file-paths=sub;subs;subtitles
sub-font=Netflix Sans
sub-font-size=42

### Audio ###
audio-file-auto=fuzzy

### Language Priority ###
# Subtitles
# Add "enm" before "eng" if you prefer honorifics.
slang=eng,en

# Audio
alang=jpn,ja

# English dub
# slang=zxx,eng,en
# alang=eng,en
# subs-with-matching-audio=forced

### Screenshots ###
screenshot-format=png
screenshot-dir="~/Screenshots/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

### ytdl ###
ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]
