include=~/.config/fuzzel/fuzzel.ini

[main]
placeholder="Browse clipboard"

# Layout
lines=40
width=189
anchor=top-left
horizontal-pad=20
vertical-pad=20
line-height=26
inner-pad=12

[border]
radius=0
