include=~/.cache/wal/fuzzel.ini

[main]
font=Maple Mono NF:size=12
terminal=foot -e
placeholder="Search apps"
prompt="➜ "
dpi-aware=no

# Layout
lines=4
width=27
horizontal-pad=19
vertical-pad=12
line-height=24
inner-pad=7

[border]
width=0
radius=20
selection-radius=14

[key-bindings]
delete-line-forward=none
next=Control+j
prev=Control+k
