-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@144.01", position = "-192x320", scale = 1.00 })
