# Sourcing external config files
$configs = $HOME/.config/hypr/configs

source= $configs/startup.conf
source= $configs/environment.conf
source= $configs/keybinds.conf
source= $configs/input.conf
source= $configs/looknfeel.conf
source= $configs/animations.conf
