-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Microstep MSI G241 0x00000026",
  mode = "1920x1080@144.01",
  position = "0x-55",
  scale = 1,
  bitdepth = 16,
})

hl.monitor({
  output = "desc:Lenovo Group Limited 0x40A9",
  disabled = true,
})
