-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Lenovo Group Limited 0x40A9",
  mode = "1920x1080@60.00",
  position = "-1280x360",
  scale = 1,
})

hl.monitor({
  output = "desc:Microstep MSI G241 0x00000026",
  disabled = true,
})
