[opener]
edit = [
  { run = "nvim \"$@\"", desc = "Neovim", block = true }
]

pdf = [
  { run = "zathura \"$@\"", desc = "Open with Zathura", orphan = true }
]

imgs = [
  { run = "feh \"$@\"", desc = "Open with feh", orphan = true}
]

[open]
rules = [
  { mime = "audio/*", use = "open" },
  { mime = "video/*", use = "open" },
  { mime = "application/pdf", use = "pdf" },
  { mime = "image/*", use = "imgs" },

  # Everything else → Neovim
  { name = "*", use = "edit" }
]

