# Wayland / Electron forcing
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Session identification
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# Cursor
env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 22
