# Wayland / Electron forcing
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Session identification
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# Qt
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland;xcb

# Firefox
env = MOZ_ENABLE_WAYLAND,1

# Cursor
env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 22
