$terminal = ghostty
$fileManager = thunar
$menu = wofi -n

$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
# bind = $mainMod, E, exec, $fileManager
bind = $mainMod, E, exec, ghostty -e yazi
bind = $mainMod, V, togglefloating
bind = ALT , SPACE, exec, $menu
bind = $mainMod, S, exec, swaync-client -t 
bind = $mainMod, P, pseudo
bind = $mainMod, W, killactive
bind = $mainMod, J, togglesplit
bind = $mainMod, F, fullscreen
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Workspace bindings
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Audio
bindel = ,XF86AudioRaiseVolume, exec, ~/.config/waybar/scripts/volume-control.sh --inc 
bindel = ,XF86AudioLowerVolume, exec, ~/.config/waybar/scripts/volume-control.sh --dec 
bindel = ,XF86AudioMute, exec, ~/.config/waybar/scripts/volume-control.sh --toggle

# Brightness
bindel = ,XF86MonBrightnessUp, exec, ~/.config/waybar/scripts/brightness.sh --inc
bindel = ,XF86MonBrightnessDown, exec, ~/.config/waybar/scripts/brightness.sh --dec 

# Mic
bind = , XF86AudioMicMute, exec, ~/.config/waybar/scripts/volume-control.sh --toggle-mic 

# Media
bindl = ,XF86AudioNext, exec, playerctl next
bindl = ,XF86AudioPause, exec, playerctl play-pause
bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioPrev, exec, playerctl previous

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Screenshots
bind = CTRL, Print, exec, grimblast copy area
bind = , Print, exec, hyprshot -m window -o ~/Screenshots/
bind = ALT, Print, exec, hyprshot -m active -m output -o ~/Screenshots/

# Emojis
bind = ALT, I, exec, wofi-emoji

# Clipboard
bind = $mainMod, C, exec, cliphist list | sed 's/^[0-9]\+\s\+//' | wofi --show dmenu -i | wl-copy

# Wallpaper / scripts
bind = ALT, W, exec, ~/.config/hypr/scripts/wallpaper.sh menu  # wallpaper menu selector
bind = ALT SHIFT, w, exec, ~/.config/hypr/scripts/wallpaper.sh manual  # random wallpaper
bind = ALT, A, exec, ~/.config/waybar/scripts/refresh.sh
bind = ALT, B, exec, ~/.config/waybar/scripts/select.sh
bind = ALT, R, exec, ~/.config/swaync/refresh.sh

# Hyprlock / Wlogout
bind = $mainMod, L, exec, hyprlock
bind = ALT, TAB, exec, wlogout -b 5 -c 30 -B 410 -T 410
