general {
    gaps_in = 1
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(255,255,255,0.03)
    col.inactive_border = rgba(255,255,255,0.015)
    resize_on_border = true
    allow_tearing = true 
    layout = dwindle
}

decoration {
    rounding = 18
    active_opacity = 1
    inactive_opacity = 0.96
    fullscreen_opacity = 1

    blur {
        enabled = true
        size = 2
        passes = 2
        new_optimizations = true
        ignore_opacity = true
        xray = false
        popups = true
    }

    shadow {
        enabled = true
        range = 6
        render_power = 3
        color = rgba(10, 12, 24, 0.33)
    }
}

dwindle {
    pseudotile    = true
    preserve_split = true
}

cursor {
    no_hardware_cursors = false
    inactive_timeout = 3
}

misc {
    vfr = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    focus_on_activate = true
}
