general {
    gaps_in = 1
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(255,255,255,0.03)
    col.inactive_border = rgba(255,255,255,0.015)
    resize_on_border = true
    allow_tearing = true 
    layout = dwindle
}

decoration {
    rounding = 16
    active_opacity = 1
    inactive_opacity = 0.96
    fullscreen_opacity = 1
    blur:enabled = false
    shadow:enabled = false
}

dwindle {
    pseudotile    = true
    preserve_split = true
}

cursor {
    no_hardware_cursors = false
    inactive_timeout = 3
}

xwayland {
    force_zero_scaling = true
}

misc {
    vfr = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    focus_on_activate = true
}
