monitor = , preferred, auto, 1

general { 
    gaps_in = 1
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(255,255,255,0.03)
    col.inactive_border = rgba(255,255,255,0.015)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

dwindle { 
    preserve_split = true
}

misc { 
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    focus_on_activate = true
}

# DECORATION
decoration {
    rounding = 10
    active_opacity = 1
    inactive_opacity = 0.92
    fullscreen_opacity = 1

    blur {
        enabled = true
        size = 3
        passes = 3
        new_optimizations = true
        ignore_opacity = false 
        xray = false
        popups = true
    }

    shadow {
        enabled = true
        range = 4 
        render_power = 2 
        color = rgba(0,0,0,0.35)
    }
}

animations {
    enabled = false
}

# INPUT
input {
    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0.0
  
    touchpad {
        natural_scroll = true
    }
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_cancel_ratio = .05
    workspace_swipe_min_speed_to_force = 0
}

device {
    name = pixart-hp-usb-optical-mouse
    sensitivity = 0
}
