monitor = , preferred, auto, 1

general { 
    gaps_in = 1
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(255,255,255,0.03)
    col.inactive_border = rgba(255,255,255,0.015)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

dwindle { 
    preserve_split = true
}

misc { 
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    focus_on_activate = true
}

# DECORATION
decoration {
    rounding = 18
    active_opacity = 1
    inactive_opacity = 0.96
    fullscreen_opacity = 1

    blur {
        enabled = true
        size = 2
        passes = 2
        new_optimizations = true
        ignore_opacity = true
        xray = false
        popups = true
    }

    shadow {
        enabled = true
        range = 6
        render_power = 3
        color = rgba(10, 12, 24, 0.33)
    }
}

animations {
    enabled = true

    bezier = linear, 0, 0, 1, 1
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92
    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
    bezier = fluent_decel, 0.1, 1, 0, 1
    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1

    # Snappier windows open/close
    animation = windowsIn,  1, 1, overshot, popin 65%
    animation = windowsOut, 1, 0.8, overshot, popin 40%

    # General windows (move/resize) – keep crisp but quick
    animation = windows, 1, 1, overshot

    # Fade – shorten it a lot for snappier overall feel
    animation = fade, 1, 1.2, md3_decel

    animation = border, 1, 10, default

    # Workspace switches stay instant
    animation = workspaces, 0
    animation = workspacesIn, 0
    animation = workspacesOut, 0
    animation = specialWorkspace, 0
    animation = specialWorkspaceIn, 0
    animation = specialWorkspaceOut, 0
}

# INPUT
input {
    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0.0
  
    touchpad {
        natural_scroll = true
    }
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_cancel_ratio = .05
    workspace_swipe_min_speed_to_force = 0
}

device {
    name = pixart-hp-usb-optical-mouse
    sensitivity = 0
}
