# Core environment
exec-once = systemctl --user import-environment  WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# UI & notifications
exec-once = waybar
exec-once = swaync
exec-once = gammastep

# Utilities & daemons
exec-once = hypridle
exec-once = shikane
exec-once = awww-daemon
exec-once = wl-paste --watch cliphist store

# Restore last wallpaper
exec-once = sleep 2 && ~/.config/hypr/scripts/wallpaper.sh restore

# Audio & power
exec-once = sleep 2 && pactl set-sink-mute @DEFAULT_SINK@ 0
exec-once = ~/.config/hypr/scripts/battery-low-notify.sh
