# Core environment
exec-once = systemctl --user import-environment  WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# UI & notifications
exec-once = waybar
exec-once = swaync
exec-once = gammastep

# Wallpaper daemon + restore
exec-once = awww-daemon
exec-once = sleep 1 && ~/.config/hypr/scripts/wallpaper.sh restore

# Utilities & daemons
exec-once = hypridle
exec-once = shikane
exec-once = wl-paste --watch cliphist store

# Audio
exec-once = pactl set-sink-mute @DEFAULT_SINK@ 0
exec-once = pactl set-source-mute @DEFAULT_SOURCE@ 1

# Power
exec-once = ~/.config/hypr/scripts/battery-low-notify.sh
