alias bye='read -r '\''REPLY?Really power off? [Y/n] '\'' || exit; [[ -z $REPLY || $REPLY = [Yy]* ]] && sudo poweroff || echo "Shutdown cancelled."'
alias ls='eza --icons=always --git --group-directories-first'
alias ll='eza -l --icons=auto --git --group-directories-first --header --time-style=long-iso'
alias pacclean='sudo pacman -Sc --noconfirm && sudo paccache -r'
alias fonts='fc-list : family | sort -u'
alias pacorphans='sudo pacman -Rns $(pacman -Qdtq) 2>/dev/null || echo "No orphans to remove."'
alias update='sudo pacman -Syu'
alias n='nvim'
alias gs='git status -s'
alias ds='git diff --staged'
alias dsn='git diff --staged | diffnav'
alias ta='tmux attach'
alias tl='tmux list-sessions'
alias tkill='tmux kill-server'
alias tks='tmux kill-session -t'
alias ssh-on='_ssh_agent_lazy'
alias ruffle='env WGPU_PRESENT_MODE=Immediate ruffle --graphics vulkan'
alias mediainfo='mediainfo --Inform="Audio;Bitrate: %BitRate% kb/s | %SamplingRate% %Hz | %BitDepth%-bit\n"'
