HISTSIZE=1000000
HISTFILE="$XDG_CACHE_HOME/zsh_history"
SAVEHIST=$HISTSIZE
setopt sharehistory
setopt hist_ignore_all_dups
setopt appendhistory
setopt hist_reduce_blanks
setopt hist_verify
setopt hist_expire_dups_first
setopt inc_append_history
setopt hist_find_no_dups
